---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mattermost-db-credentials
  namespace: mattermost
spec:
  encryptedData:
    DB_CONNECTION_STRING: AgAumY66Tz94tKhKnhm4hAUNfvbk/Fj91irbWlGAJ7k+Nn5zGhMS1rJZVYRO0nyznKeqWJAnHb9RzSsOwL9hgCyar3XXdIb4hT9TaGSCYqn0ZZTUgQnIgAv4L9JTAiXkQc6IFZKdp3UxHc622nt2Imuutawr682lM0DD06RVq6nc7dykPtWDEXxsGBfzRSWBLyvjLuwR5k6RWjqiTKqiAKMXDjivVD/8Oebuh1FKp1g1gD28n0fMZeWou0kEiWVBfiOSYpGLLfTlN2GKBHHGl08SeZ6neqVcpxZbb6vWrV0u0QBgvVYhNL42J8slsOZqhMuYtFoYonckjXlzWsMLx6iVdZ6JYg68CGXZwN3NROsY37wZz5R63dBrCS4JtM0UyrdsU5k0R+HXUqHpk0gooXLmJ2k4Qq6GLeY8NI2sE7wNNtPkgP7z3V3GrJtXyQu0jFTbWYyd7BK3KwpjIri5k7hcyCeFmwPNsTu3GM0xfl813U+rRM2gm8c3VF1e34IOs8STLHES2TAFv8x/BkEY9+IfzphCovFe8myJ3Z8KquzdEDUS+WMkMR9x4L6qIOoh5/i57wFML+RXWMqK3M+nVhS4PXBPW+EHvqq1KR6jLuhFKOIHuqBR5g+aNP2I9ERFwoXF7ta7wq6DJTFVuS1cliyZ3w8jDG/wHnII+ZPL2NTZNanz/GGx08+AUyD+Zggmj49MzUOU5NTM14kRcSMP3LVYjCKE39Yj4wwPBIfKGXDeVnoIFE6aQ64vw/mBGSiWfNCkDUNuEg6ojY9DgqkaMn7yhawzb9n96vFRZLcb47Qhl7vEVxfUJPHW4meyqqKaqKXaVyTb1ad6HBm/DJL7ZcTSO7ybcErRJnLef0uFX9k=
  template:
    metadata:
      name: mattermost-db-credentials
      namespace: mattermost
