---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mattermost-db-postgresql
  namespace: mattermost
spec:
  encryptedData:
    password: AgAg36rnJ6gFH0f42eiVg8Eeku9H9NsJxxEeo5MzmWvzZudQ70MUpZPjHX0ccnPpafNfedxcfeCGenJ5pCunqU+atSYzAf1BKBNYPwW+tjFmpJt3aolOaAqhHPvteT/bxVD5Q9cVkUI/nKwWeZU6TkNWUl1LFLHFOSNo/Vn/wHB1a3+vvV8qk3JY1++sKgfMdhNpBvJPMwCorzVVZZo39IzTgQgCNMdcQOSdSQhAV/wy487YDkRZORjDNi3YnOoedJamZMCqIS48Xks4srgOz83FTRJwnxxD5QGBWNl5q0cXpOWoh5rfY79j1EFsvAgKsLnAdjIo/9KVLGvMXHvDYUuIP+civGC38LD7/G0AZYLwNDWxsgBzbh3hR1CZIuTEnnlUKSubjc5VaEKfLsrR3Iwyz4FtbdAr2JZTCEqFddqaysgdRzXRlNmyeAqNVRz41A5u2GD6QOjDVduDExWlHQ6A9VEBUBUk5dpSoF9JRy64+SeDAWJC5EyeXXgNG4KglahpQPFzaQUTMYN/wtw/5hVD3UYc9jF7fNc++cFACexrxeq4AXsNAQZuhGpvKxnyNx6pYwpNwXvA1CC1GktiDURRAwWf/WRZ0zPIT9tdVolO/T/R0XpfAMye6/sh2shlUFFeVm+2tKfGUDPFaUrDko83pll00Ulhmj3ldVaMP6Oc6NYojHgXe+VV9CW9FwP0q7Ts49vhI3BVqKGaZD+9ySlPnFxCuL3S
    postgres-password: AgAnWT3MRi9OqBpTAn12owhqPl8jgOH9PwuyLyg+KRERBQfR6Qjj4TIU3+qHlmd+XiyvYiX4kx2Hbb77OXLLdpsTQusjNlEjPitHO++JtVFJ/EhOENrFHS/Mgx3X8ScVivQcdxXBhGBPcm0+Shb6Ipo76pNqqt6jcXFM40wXAMMb+yPWWiC7K0F6lym3gS2aUESQQflRyxzvoc93mz/N6E0Sh1jtZZRBqWi9xR9S+c1I4d2fdFUZ4nT9NLeTrTb8AMXDAEZlz+C5B635JQv0DZqtWnxlwzLg/OO2OIPtSOt1ZbKZUuS41jN6Wuo1olpbZOJOReWycKzvW19EJLowyf7cI6Rnx0dlgZoKwDTMNeDt4ZLo2IJO+IVMyNelrupGtPtDB15s1aN90n5Jh3P26+ScbRzeVSJ4wDGPNAFXLPSb21zkDq++wXJVm16XPNo2zBD4hKCdnXa8majb31/AoD+XlQVmqt47g0zL/gH2eVwOLY4FLsoI4h9ZXR5um3PxjWhQI94YSGpFqkdD4Cc+xfWc9Ma4q9qQHIpbHRg2x8Xb8EojF0Nqn8u/VDwKT/FMku5E2peqlyuHKUkfS6LEZWHv85ORJVfrFcKUkV4xyz3jvDJHJCG7/HDkbLzFuY2FklC3JoSmBibBhd75JRgaTeQ+Z61M73vr/lB3z3v/mKfuLqPAgBS6Or5l5+J/ifl8zzs67cD0e3H+uHxPQk+Y8B8NZyiA3fwR
  template:
    metadata:
      name: mattermost-db-postgresql
      namespace: mattermost
