---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mattermost-minio-credentials
  namespace: mattermost
spec:
  encryptedData:
    accesskey: AgCxTIRqwMsJYXoiyPhkbVL86+nMqJ7oDlYwPFicCWtCPHOG6OPuQ3ZZX7XnkunqCVf9/wklshCkdeC+wK2k4/db8ie/OucRASsxmnpKDvMV2hW/BmE9Kv76Hlg1S0OlKkCOy3PAIjH5+yChwZTxtjXWpImxGV1Z6SxAXqN/EBkvfEPkYdbQ9VUFFKPnnumit8Gg28jLympN/L1adv3aWKpb4+rfILvHQNXCeGleku+7wSKoCHQka1glsAyGGXOXrAqvBWIkf14NH7k2SO4iFEPgIzwZS0j7QC1t2W6SOW0yZUKxdVf8llESjSe1/HuvZNk3pykUzb8olNEXMhek/C8PD1dMYGLLMA45oiqJMCDh5hTj0gOWiRRJYYHhHC/NNZIEIDcAEZtFnyWtZpX3n7wVcKuq7p+49IvoZbTnJ9/5IqMs5MzTtM4NONOOtqzys3R1WPxbg7z0/hqIYjoAhpMg+99YLXQuOlyWTLovmGZ0P2PwEUxgcdJZMuSyOQxMDWvX2/Gb9X2ifbNutexENj2SZohO+lJsiGT/X0A9tZOMJWOGrukO2NuwDVJzydciIApw2lHkg5rFfJx4JOBM7pzAoWpKUiVjbRQFQEMIw4xrHAziy1d/8nzsZvkGYnZuuS5GoyV96GEHzTrLWkdqwWoWrZDYQIsJpu9N68siJrsm9dYwsyTfl5870t9jTINR4PEnkH+5aJiMw/2j/iu8SJ4/
    secretkey: AgBcIzpd+jZskehMPCxE0Q0x4DvtgQrNmegab9xX4UF5McZFDrjd/sHTqJ53+36r7TiBQVtBiCoDE4Hfv05S4OMpbYIhMxgZwLviC7YEd2jQ7b0zlYzMKd2O2OWBhSeJmAMxSlEjndQg+/7eA29MoPRnq9n8UjeWw5Ty0RmdJsB3TKMOZCGg5bGtDsM0HHGC1pP5LOptpZASYeOLluuwX/L9HvikeDUO8oitPH7e0WQ8XGR2tm3ozNobnW2J4pscshCNSj1pSX802tZJHSdTX6GkGwAZxDzIbB0JIqEJrXDtAMq88ZpMMlnJahfSGHnyW6yIgQ0akrihoOIKEA4wrbNSkyFGhVRckiMx9SzxM8XGdkB3w0YZSopjcptz5k7yGf4DahcSPFDJpPkcxDHsAZ5XpgHrHSxMa1d3D3jzwDG0vFUjtvdNVQXZU1cc9EaKs0ZD4+DQAvgyj9D66BMU3rzZe2hpfgXPe86pKfb2jkXbCWJmpAOWH5ORdFTAN1Q4FqeQCCu9Bj5uYd5tJVh1a0DUXTkMhB14mOpMvwwW/qDbDKjyCJ7yxtVSvXT1kUfwpN4uZKn1Ffvh3UCso73hGBjU8Mx+sIFecpGmuNi8vEybn6WTiBpATsvvXUE8PkMx9lpat4i//tYotV1gXujLOQs60fCm13+mOthkKPVEx0FayVLp+HVkWElPN0Q3/jWLtNkHkUW3RUzPnOnHo72ppIwmNDO2d090Ee7kZM2WjBvkqg==
  template:
    metadata:
      name: mattermost-minio-credentials
      namespace: mattermost
