#!/usr/bin/env bash
# scripts/03-bootstrap-flux.sh
# 1. Renders cluster-config.yaml from .env values
# 2. Renders MetalLB IPAddressPool from .env values
# 3. Commits infrastructure layer to Git
# 4. Runs flux bootstrap github (installs Flux controllers + wires GitRepository)
# 5. Applies cluster-config ConfigMap so Flux variable substitution works
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
source "$SCRIPT_DIR/lib/common.sh"
load_env "$ROOT_DIR/.env"

log_section "03 — Bootstrap FluxCD"

require_tool flux
require_tool kubectl
require_tool git

# ── Validate we can reach the cluster ───────────────────────
kubectl cluster-info > /dev/null 2>&1 || {
  log_error "Cannot reach Kubernetes cluster. Is it running and kubectl configured?"
  exit 1
}
log_ok "Cluster reachable"

# ── 1. Render cluster-config.yaml ───────────────────────────
log_step "Rendering clusters/production/cluster-config.yaml"
cat > "$ROOT_DIR/clusters/production/cluster-config.yaml" <<EOF
# AUTO-GENERATED by scripts/03-bootstrap-flux.sh — safe to commit
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-values
  namespace: flux-system
data:
  DOMAIN: "${DOMAIN}"
  SERVER_IP: "${SERVER_IP}"
  LETSENCRYPT_EMAIL: "${LETSENCRYPT_EMAIL}"
  CLUSTER_NAME: "${CLUSTER_NAME}"
EOF
log_ok "cluster-config.yaml rendered"

# ── 2. Render MetalLB IPAddressPool ─────────────────────────
log_step "Rendering MetalLB IPAddressPool"
# If METALLB_IP_RANGE is a single IP (e.g. 1.2.3.4/32), convert to pool format
if [[ "$METALLB_IP_RANGE" == *"/"* ]]; then
  # CIDR notation — MetalLB accepts this directly for address pools
  POOL_ADDR="$METALLB_IP_RANGE"
else
  # Already a range like 172.18.0.200-172.18.0.250
  POOL_ADDR="$METALLB_IP_RANGE"
fi

cat > "$ROOT_DIR/infrastructure/metallb/ipaddresspool.yaml" <<EOF
# AUTO-GENERATED by scripts/03-bootstrap-flux.sh — safe to commit
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-pool
  namespace: metallb-system
spec:
  addresses:
    - ${POOL_ADDR}
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default-l2advert
  namespace: metallb-system
spec:
  ipAddressPools:
    - default-pool
EOF
log_ok "MetalLB IPAddressPool rendered (range: $POOL_ADDR)"

# ── 3. Commit infrastructure layer ──────────────────────────
log_step "Committing rendered config and infrastructure layer"
cd "$ROOT_DIR"

# Initialise git repo if not already done
if [[ ! -d ".git" ]]; then
  git init
  git remote add origin "https://github.com/${GITHUB_USER}/${GITHUB_REPO}.git"
  log_ok "Git repo initialised"
fi

git add \
  clusters/production/cluster-config.yaml \
  infrastructure/ \
  clusters/production/infrastructure.yaml \
  kind/ \
  .gitignore \
  .env.example

git diff --cached --quiet && {
  log_info "Nothing new to commit (infrastructure already up to date)"
} || {
  git commit -m "feat: add infrastructure layer (sealed-secrets, metallb, nginx, cert-manager, mattermost-operator)"
  log_ok "Infrastructure layer committed"
}

# ── 4. Run flux bootstrap ────────────────────────────────────
log_step "Running flux bootstrap github"
flux bootstrap github \
  --owner="${GITHUB_USER}" \
  --repository="${GITHUB_REPO}" \
  --branch="${GITHUB_BRANCH}" \
  --path="clusters/${CLUSTER_NAME}" \
  --personal \
  --token-auth

log_ok "Flux bootstrapped"

# Pull bootstrap commits that Flux pushed
git pull --rebase origin "${GITHUB_BRANCH}"

# ── 5. Apply cluster-config ConfigMap immediately ───────────
log_step "Applying cluster-values ConfigMap to flux-system namespace"
kubectl apply -f "$ROOT_DIR/clusters/production/cluster-config.yaml"
log_ok "cluster-values ConfigMap applied"

log_section "03 Complete"
echo "  FluxCD is now watching: https://github.com/${GITHUB_USER}/${GITHUB_REPO}"
echo "  Path on cluster:        clusters/${CLUSTER_NAME}"
echo ""
echo "Next step:"
echo "  bash scripts/04-wait-and-seal.sh"
